import NameList from "../_components/NameList";

const names = {
  roses: [
    "Marlon Lambot",
    "Romar Lambot",
    "Aljur Lambot",
    "Arby Lambot",
    "Zaid Mohammed",
    "Ian Damian",
    "Kim Chester Moreno",
    "Liehn Empleo",
    "Jeff Bonaobra",
    "Kenn Russel Castillo",
    "Leander Bulatao",
    "John Mig Papa",
    "Nathaniel Amber Nones",
    "Kristoff Janrick Janda",
    "Shane Lloyd Bejo",
    "Axel Aaron Bruzo",
    "Dustin Reyes",
    "Kendrick Vargas",
  ],
  treasures: [
    "Missy Lambot",
    "Myth Aera Lambot",
    "Kristof Lambot",
    "Cristine Lambot",
    "Daniela Damian",
    "Irish De Rama",
    "Marcicon Anglit",
    "Evelyn Del Mundo",
    "Kathlyn Kate Hernandez",
    "Aaliyah Stephanie Sombilon",
    "Chierra Mae Concepcion",
    "Anne Bernadeth Mejino",
    "Rhianna Andrei Labio",
    "Francheska Pucyutan",
    "Alexandra Visperas",
    "Jazzmeen Mundin",
    "Margarette Laas",
    "Cyrine Manalo",
  ],
  yellowBills: [
    "Mary Jane Lambot",
    "Kamille Moreno",
    "Melaica Constantino",
    "Maryknoll Lizano",
    "Michelle Domingo",
    "Zyreeh Empleo",
    "Gilbert Lizano",
    "Jun Damian",
    "Frysthine Anglit - Sarmiento",
    "Lovely Torres - Ochoa",
    "Ester Torres",
    "Shanea Hudieras",
    "Marife Baylon",
    "Jericho Agapito",
    "Kuya Rodel",
    "Sir Pulis",
  ],
  blueBills: [
    "Rowena Lambot",
    "Marru Lambot - Anglit",
    "Jem Mar Anglit",
    "Ronalie Lambot",
    "Mila Lambot - Moreno",
    "Gener Lambot",
    "Amado Lambot",
    "Thess Lambot - Domingo",
    "Glo Potencio - Lizano",
    "Randy Lizano",
    "Cristy Lizano - Empleo",
    "Connie Anglit",
    "Ninong Buboy Fumera",
    "Ninong Mawe Gabitanan",
    "Ninong Greg De Guzman",
    "Ninang Imelda Sarmiento",
    "Doc. Alexander Lim",
    "Doc Aireen Boguiro",
  ],
};

export default function Page() {
  return (
    <main className="flex min-h-screen flex-col bg-white px-4 py-24 dark:bg-gray-700">
      <NameList names={names.roses} title="18 Roses" />
    </main>
  );
}
